-- MySQL Script generated by MySQL Workbench
-- Sat Mar 24 19:49:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TCCData
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TCCData` ;

-- -----------------------------------------------------
-- Schema TCCData
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TCCData` DEFAULT CHARACTER SET utf8 ;
USE `TCCData` ;

-- -----------------------------------------------------
-- Table `TCCData`.`perfis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TCCData`.`perfis` ;

CREATE TABLE IF NOT EXISTS `TCCData`.`perfis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL COMMENT 'Tipos:\n0- Admin \n1- Supervisor TCC\n2- Orientador\n3- Coorientador\n4-Orientado',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TCCData`.`acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TCCData`.`acessos` ;

CREATE TABLE IF NOT EXISTS `TCCData`.`acessos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `perfis_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_acessos_perfis1_idx` (`perfis_id` ASC),
  CONSTRAINT `fk_acessos_perfis1`
    FOREIGN KEY (`perfis_id`)
    REFERENCES `TCCData`.`perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TCCData`.`enderecos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TCCData`.`enderecos` ;

CREATE TABLE IF NOT EXISTS `TCCData`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TCCData`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TCCData`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `TCCData`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `orgao_expeditor` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `acessos_id` INT NOT NULL,
  `enderecos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_acessos1_idx` (`acessos_id` ASC),
  INDEX `fk_usuarios_enderecos1_idx` (`enderecos_id` ASC),
  CONSTRAINT `fk_usuarios_acessos1`
    FOREIGN KEY (`acessos_id`)
    REFERENCES `TCCData`.`acessos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_enderecos1`
    FOREIGN KEY (`enderecos_id`)
    REFERENCES `TCCData`.`enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TCCData`.`professores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TCCData`.`professores` ;

CREATE TABLE IF NOT EXISTS `TCCData`.`professores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acessos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `orientadores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_orientadores_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_orientadores_acessos1_idx` (`acessos_id` ASC),
  CONSTRAINT `fk_usuario_orientadores_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `TCCData`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orientadores_acessos1`
    FOREIGN KEY (`acessos_id`)
    REFERENCES `TCCData`.`acessos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TCCData`.`alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TCCData`.`alunos` ;

CREATE TABLE IF NOT EXISTS `TCCData`.`alunos` (
  `idorientandos` INT NOT NULL AUTO_INCREMENT,
  `ra` VARCHAR(45) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `acessos_id` INT NOT NULL,
  PRIMARY KEY (`idorientandos`),
  INDEX `fk_orientandos_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_orientandos_acessos1_idx` (`acessos_id` ASC),
  CONSTRAINT `fk_orientandos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `TCCData`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orientandos_acessos1`
    FOREIGN KEY (`acessos_id`)
    REFERENCES `TCCData`.`acessos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TCCData`.`coorientadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TCCData`.`coorientadores` ;

CREATE TABLE IF NOT EXISTS `TCCData`.`coorientadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acessos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `titulacao` VARCHAR(45) NOT NULL,
  `instituicao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coorientadores_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_coorientadores_acessos1_idx` (`acessos_id` ASC),
  CONSTRAINT `fk_coorientadores_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `TCCData`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coorientadores_acessos1`
    FOREIGN KEY (`acessos_id`)
    REFERENCES `TCCData`.`acessos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
